apps/blockchain/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from apps.blockchain import views, datatables

app_name = 'blockchain'

router = DefaultRouter()
router.register(r'logs', datatables.LogDataTableView, basename='logs')

urlpatterns = [
                  path('', views.ExplorerView.as_view(), name='explorer'),
                  path('network/', views.NetworkView.as_view(), name='network'),
              ] + router.urls

apps/challenge/challenge_client/urls.py
from django.conf import settings
from django.urls import path

from apps.challenge.challenge_client import views

urlpatterns = [
    path('', views.ChallengeListView.as_view(), name='challenge-list'),
    path('<uuid:pk>/enroll/', views.EnrollInChallengeView.as_view(), name='challenge-enroll'),
    path('<uuid:pk>/enroll/not/', views.NotEnrolledTemplateView.as_view(), name='challenge-not-enrolled'),
    path('<uuid:pk>/', views.ChallengeDetailView.as_view(), name='challenge-detail'),
    path('<uuid:pk>/datasets/', views.ChallengeDatasetsView.as_view(), name='challenge-datasets'),
    path('<uuid:pk>/exports/<uuid:job_pk>/', views.ExportDetailView.as_view(), name='challenge-datasets-exports-detail'),
    path('<uuid:pk>/exports/<uuid:job_pk>/actions/', views.ExportDetailActionsView.as_view(),
         name='challenge-datasets-exports-detail-actions'),
    path('<uuid:pk>/exports/', views.ExportListView.as_view(), name='challenge-datasets-exports'),
    path('<uuid:pk>/datasets/overview/', views.ChallengeDatasetsOverviewView.as_view(),
         name='challenge-datasets-overview'),
    path('<uuid:pk>/datasets/<uuid:dataset_pk>/', views.ChallengeDatasetsDetailView.as_view(),
         name='challenge-datasets-detail'),
    path('<uuid:pk>/datasets/<uuid:dataset_pk>/actions/', views.ChallengeDatasetsDetailActionView.as_view(),
         name='challenge-datasets-detail-action'),
    path('<uuid:pk>/submissions/', views.ChallengeSubmissionsListView.as_view(), name='challenge-submission-list'),
    path('<uuid:pk>/submissions/create/', views.ChallengeSubmissionCreateView.as_view(),
         name='challenge-submission-create'),
    path('<uuid:pk>/submissions/<uuid:submission_pk>/', views.ChallengeSubmissionsDetailView.as_view(),
         name='challenge-submission-detail'),
    path('<uuid:pk>/submissions/<uuid:submission_pk>/results/<uuid:status_pk>/',
         views.ChallengeResultDetailView.as_view(), name='challenge-submission-result-detail'),
    path('<uuid:pk>/leaderboard/', views.ChallengeLeaderboardView.as_view(), name='challenge-leaderboard'),
    path('<uuid:pk>/log/', views.LogView.as_view(), name='log'),
    path('<uuid:pk>/<uuid:submission_pk>/artifact/', views.ArtefactView.as_view(), name='artifact'),
]

if settings.HUB_ENABLE_REGISTRATION:
    urlpatterns += [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('register/success/', views.RegisterSuccessView.as_view(), name='register_success'),
]

apps/challenge/urls.py
from django.urls import path, include

from apps.challenge import views

urlpatterns = [
    path('', views.ListView.as_view(), name='list'),
    path('create', views.CreateChallengeView.as_view(), name='create'),
    path('<uuid:pk>/website/', include('apps.challenge.website.urls'), name='website'),
    path('<uuid:pk>/', views.RedirectToDatasetListView.as_view(), name='detail'),
    path('<uuid:pk>/update/', views.UpdateChallengeFormView.as_view(), name='update'),
    path('<uuid:pk>/publish/', views.PublishView.as_view(), name='publish'),
    path('<uuid:pk>/pipeline/create/', views.CreatePipelineView.as_view(), name='pipeline-create'),
    path('<uuid:pk>/datasets/', include(('apps.challenge.challenge_dataset.urls', 'challenge_dataset'))),
    path('<uuid:pk>/submissions/', include(('apps.challenge.challenge_submission.urls', 'challenge_submission'))),
    path('<uuid:pk>/leaderboard/', include(('apps.challenge.challenge_leaderboard.urls', 'challenge_leaderboard'))),
    path('<uuid:pk>/evaluation-code/', views.EvaluationCodeView.as_view(), name='evaluation-code'),

]

apps/challenge/website/urls.py
from django.urls import path

from apps.challenge.website.views import CreateWebsiteView, PreviewView
app_name = 'website'

urlpatterns = [
    path('create/', view=CreateWebsiteView.as_view(), name='create'),
    path('<uuid:website_pk>/preview/', view=PreviewView.as_view(), name='preview'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from apps.federation.inbox.views import InboxView


urlpatterns = [
                  # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
                  # path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
                  # # Django Admin, use {% url 'admin:index' %}
                  path('api/storage/', include('apps.storage.urls_api'), name='api-storage'),
                  path('api/study/', include('apps.study_management.urls_api')),
                  path(settings.ADMIN_URL, admin.site.urls),
                  path('federation/', include(('apps.federation.urls', 'federation'))),
                  path('user/', include(('apps.user.urls', 'user'))),
                  path('api/inbox/', InboxView.as_view(), name='inbox'),
                  # User management
                  # path("users/", include("centauron.users.urls", namespace="users")),
                  # path("accounts/", include("django.contrib.auth.urls")),
                  path("accounts/", include("allauth.urls")),

                  # Your stuff: custom urls includes go here
                  path('projects/', include(('apps.project.urls', 'project'))),
                  path('challenge/', include(('apps.challenge.urls', 'challenge'))),
                  path('computing/', include(('apps.computing.urls', 'computing'))),
                  path('study/', include(('apps.study_management.urls', 'study_management'))),
                  path('share/', include(('apps.share.urls', 'share'))),
                  path('terminology/', include(('apps.terminology.urls', 'terminology'))),
                  path('viewer/', include(('apps.viewer.urls', 'viewer'))),
                  path('blockchain/', include('apps.blockchain.urls', namespace='blockchain')),
                  # path('share/', include(('apps.share.urls', 'share'))),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

challenge_client_path = '' if settings.IS_CHALLENGE_HUB else 'challenge/client/'

urlpatterns += [path(challenge_client_path, include(('apps.challenge.challenge_client.urls', 'challenge_client')))]
if not settings.IS_CHALLENGE_HUB:
    urlpatterns += [
        path('', include(('apps.core.urls', 'core'))),
    ]
# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    # path("auth-token/", obtain_auth_token),
    # path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    # path(
    #     "api/docs/",
    #     SpectacularSwaggerView.as_view(url_name="api-schema"),
    #     name="api-d
    #
    #     ocs",
    # ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/challenge/challenge_dataset/views.py
import csv
import itertools
import json
from pathlib import Path
from typing import Any, Dict
from uuid import UUID

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import StreamingHttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.views import View
from django.views.generic import DetailView as DjangoDetailView, CreateView as DjangoCreateView, FormView, UpdateView

from apps.blockchain.messages import AddMessage, Object
from apps.blockchain.models import Log
from apps.challenge.challenge_dataset import forms
from apps.challenge.challenge_dataset.forms import QueryForm
from apps.challenge.challenge_dataset.models import Dataset
from apps.challenge.challenge_dataset.tasks import import_csv
from apps.challenge.views import BaseTabView, ChallengeContextMixin
from apps.core import identifier
from apps.core.views import BaseTableActionView
from apps.project.project_case.models import Case
from apps.storage.models import File
from apps.storage.utils import move_to_tmp_dir
from apps.terminology.models import Code


class DatasetContextMixin(ChallengeContextMixin):

    def get_dataset_id(self) -> UUID | None:
        return self.kwargs.get('dataset_pk')

    def get_dataset(self) -> Dataset:
        return Dataset.objects.filter(challenge_id=self.get_challenge_id()).get(pk=self.get_dataset_id())

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx['dataset'] = self.get_dataset()
        return ctx


class ListView(BaseTabView):
    template_name = 'challenge/challenge_dataset/tab.html'

    def get_tab_name(self):
        return 'datasets'


class CreateView(LoginRequiredMixin, ChallengeContextMixin, DjangoCreateView):
    template_name = 'challenge/challenge_dataset/create.html'
    form_class = forms.DataSetCreateForm

    def get_queryset(self):
        return Dataset.objects.filter(challenge_id=self.get_challenge_id())

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.created_by = self.request.user.profile
        obj.identifier = identifier.create_random('dataset')
        obj.challenge_id = self.get_challenge_id()
        obj.origin = self.request.user.profile
        obj.encrypted = False
        # obj.is_public = True
        obj.save()
        obj.broadcast_create_event()
        return redirect(obj)


class DetailView(LoginRequiredMixin, DatasetContextMixin, DjangoDetailView):
    template_name = 'challenge/challenge_dataset/detail.html'

    def get_object(self, queryset=None):
        return self.get_dataset()


class ImportDataCSVView(LoginRequiredMixin, DatasetContextMixin, FormView):
    template_name = 'challenge/challenge_dataset/import_csv.html'
    form_class = forms.ImportDataForm

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update({
            'challenge': self.get_challenge()
        })
        return ctx

    def get_success_url(self):
        return self.get_dataset().get_absolute_url()

    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw.update(dict(dataset=self.get_dataset()))
        return kw

    def form_valid(self, form):
        messages.success(self.request, 'Data will be imported.')
        file = form.cleaned_data['file']
        dst = move_to_tmp_dir(Path(file.temporary_file_path()))
        import_csv.delay(self.request.user.profile.id_as_str, str(dst.resolve()), self.get_dataset_id())
        messages.success(self.request, 'Files will be imported.')
        return redirect(self.get_dataset().get_absolute_url())


class ImportFromProjectView(LoginRequiredMixin, DatasetContextMixin, View):

    def post(self, request, pk, dataset_pk, **kwargs):
        query = json.loads(request.POST.get('query_filter'))
        dataset = self.get_dataset()
        dataset.import_(query['model'], query['filter'])

        messages.success(request, 'Data imported into dataset.')
        return redirect('challenge:challenge_dataset:detail', pk=pk, dataset_pk=dataset_pk)


class QueryView(LoginRequiredMixin, DatasetContextMixin, FormView):
    template_name = 'challenge/challenge_dataset/query/query.html'
    form_class = QueryForm

    def get_form_kwargs(self) -> dict[str, Any]:
        ctx = super().get_form_kwargs()
        ctx['dataset'] = self.get_dataset()
        return ctx

    def form_valid(self, form):
        data = form.cleaned_data
        case_name = data.get('case_name', '').strip()
        qs = Case.objects.filter(projects__pk=self.get_challenge().project_id, origin__in=data['nodes'])
        terms_pk = data['term_ids'].values_list('pk', flat=True)
        if terms_pk.count() > 0:
            qs = qs.filter(files__codes__in=Code.objects.filter(pk__in=terms_pk))
        if len(case_name) > 0:
            qs = qs.filter(name__iexact=case_name)
        # current_user = self.request.user.profile

        if 'button_import' not in form.data:
            ctx = {'results': qs}
            return render(self.request, 'challenge/challenge_dataset/query/results.html', ctx)

        dataset = self.get_dataset()
        dataset.cases.add(*qs.all())
        dataset.files.add(*File.objects.filter(case__in=qs))

        msg = AddMessage(
            actor=self.request.user.profile.to_actor(),
            object=Object(model="slide", value=list(qs.values_list('identifier', flat=True))),
            context={"dataset": dataset.to_identifiable(), "challenge": self.get_challenge().to_identifiable()},
        )
        Log.send_broadcast(msg)

        return render(self.request, 'challenge/challenge_dataset/query/success.html')

    def query(self, request, qs):
        ctx = {
            'results': qs
        }
        return render(request, 'challenge/challenge_dataset/query/results.html', ctx)

    def import_(self, request, pk, qs, model, query_filter):
        success = True
        ctx = {
            'success': success,
            'filter': {'filter': query_filter, 'model': model}
        }
        return render(request, 'challenge/challenge_dataset/query/import.html', ctx)

    # def post(self, request, pk, **kwargs):
    #     action_is_query = request.POST.get('import', 'query').lower() != 'import'
    #     raw_q = request.POST.get('query', '{}')
    #     if len(raw_q.strip()) == 0:
    #         raw_q = '{}'
    #     query = json.loads(raw_q)
    #     selected_model = request.POST.get('model')
    #     if selected_model == 'case':
    #         model = Case
    #     else:
    #         model = File
    #     query_filter = {'projects__id': pk, **query}
    #     try:
    #         qs = model.objects.filter(**query_filter)
    #     except ValidationError as e:
    #         logging.error(e)
    #         return render(request, 'project/../../../templates/challenge/challenge_dataset/query/error.html',
    #                       {'message': str(e)})
    #
    #     if action_is_query:
    #         return self.query(request, qs)
    #     else:
    #         return self.import_(request, pk, qs, selected_model, query_filter)

class FileTableActionView(DatasetContextMixin, BaseTableActionView):
    model = File

    def get_success_url(self) -> str:
        return self.request.META.get('HTTP_REFERER')

    def action(self, **kwargs):
        qs = self.get_queryset()
        data = self.request.POST
        if data.get('remove_files') is not None:
            self.get_dataset().remove_files(qs)
            messages.success(self.request, f'{qs.count()} file(s) removed from dataset.')

class UpdateDatasetFormView(LoginRequiredMixin, SuccessMessageMixin, DatasetContextMixin, UpdateView):
    form_class = forms.UpdateDatasetForm
    success_message = 'Dataset updated.'
    template_name = 'challenge/challenge_dataset/update.html'

    def get_object(self, queryset=None):
        return self.get_dataset()

    def get_success_url(self) -> str:
        return reverse('challenge:challenge_dataset:update', kwargs={'pk': self.get_challenge_id(), 'dataset_pk': self.object.pk})



class ExportAsCSVView(LoginRequiredMixin, DatasetContextMixin, View):

    def post(self, request, **kwargs):
        dataset = self.get_dataset()
        dst = f'{slugify(dataset.name)}-{timezone.now().isoformat()}.csv'

        # https://docs.djangoproject.com/en/5.0/howto/outputting-csv/
        class Echo:
            def write(self, value):
                return value

        def get_rows():
            files = dataset.files.all()
            for f in files:
                yield [f.id_as_str, f.identifier, f.case.name, f.name, f.path, f.original_path, f.original_filename,
                       f.origin.identifier, f.imported]

        FIELDS = ['id', 'identifier', 'case', 'name', 'path', 'original_path', 'original_filename', 'origin',
                  'imported']

        writer = csv.writer(Echo())
        return StreamingHttpResponse(
            (writer.writerow(row) for row in
             itertools.chain([FIELDS], get_rows())),
            content_type="text/csv",
            headers={
                "Content-Disposition": f'attachment; filename="{dst}"'},
        )

templates/challenge/challenge_client/base.html
{% load static i18n %}{% load render_bundle from webpack_loader %}<!doctype html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="x-ua-compatible" content="ie=edge"/>
  <title>{% block title %}CENTAURON{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  {% include 'includes/styles.html' %}
  {% block css %}
    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    {% render_bundle 'project' 'css' %} {% endblock %}

  {% include 'includes/scripts.html' %}

  <!-- Le javascript
    ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  <!-- Vendor dependencies bundled as one file -->
  {% render_bundle 'vendors' 'js' attrs='defer' %}

  <!-- place project specific Javascript in this file -->
  {% render_bundle 'project' 'js' attrs='defer' %}

  {% block javascript %}

  {% endblock javascript %}


</head>

<body>
<div class="page">
  {% block header %}
    {% include 'challenge/challenge_client/header.html' %}
    {% block navbar %}
      {% include 'challenge/challenge_client/navbar.html' %}
    {% endblock %}
  {% endblock %}
  {% if messages %}
    <div class="container-xl">
      {% for message in messages %}
        <div
          class="alert {% if message.tags %} alert-{{ message.tags }} {% if 'error' in message.tags %} alert-danger {% endif %} {% endif %}">
          <div class="container">{{ message }}</div>
        </div>
      {% endfor %}
    </div>
  {% endif %}
  {% block content %}
    <p>Default content...</p>
  {% endblock content %}

</div>
<!-- /container -->

{% block modal %}{% endblock modal %}
{% block inline_javascript %}
  {%comment %} Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
    {% endcomment %} {% endblock inline_javascript %}
</body>
</html>

templates/challenge/challenge_client/challenge_title.html
{{ challenge.name }}

templates/challenge/challenge_client/datasets.html
{% extends 'challenge/challenge_client/detail.html' %}
{% load core_tags %}
{% block content %}
  <div class="page-wrapper">
    <div class="page-header d-print-none">
      <div class="container-xl">
        <div class="row g-2 align-items-center">
          <div class="col">
            <h2 class="page-title">
              Datasets
            </h2>
          </div>
          <div class="col-auto ms-auto d-print-none">
            <div class="btn-list">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="page-body">
      <div class="container-xl">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-body">
                {{ challenge.description|markdownify|safe }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/challenge/challenge_client/detail.html
{% extends 'challenge/challenge_client/base.html' %}
{% load core_tags challenge_client_tags %}
{% block title %}{{ challenge.name }} | {{ block.super }}{% endblock %}
{% block header %}
  {% with site_title='challenge/challenge_client/challenge_title.html' %}
    {{ block.super }}
  {% endwith %}
{% endblock %}
{% block navbar %}
  {% with site_navigation='challenge/challenge_client/navigation-challenge.html' %}
    {{ block.super }}
  {% endwith %}
{% endblock %}
{% block content %}
  <div class="page-wrapper">
    <div class="page-header d-print-none">
      <div class="container-xl">
        <div class="row g-2 align-items-center">
          <div class="col">
            <h2 class="page-title">
              Welcome to {{ challenge.name }}
            </h2>
          </div>
          <div class="col-auto ms-auto d-print-none">
            {% is_enrolled request challenge as en %}
            {% if not en %}
              <a href="{% url 'challenge_client:challenge-enroll' challenge.pk %}"
                 class="btn btn-primary d-none d-sm-inline-block">Enroll</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    <div class="page-body">
      <div class="container-xl">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-body">
                {{ challenge.description|markdownify|safe }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/challenge/challenge_client/enroll.html
{% extends 'challenge/challenge_client/base.html' %}
{% block navbar %}
{% endblock %}
{% block content %}
  <div class="page-wrapper">
    <div class="page-header d-print-none">
      <div class="container-xl">
        <div class="row g-2 align-items-center">
          <div class="col">
            <h2 class="page-title">
              Enroll to <em>{{ challenge.name }}</em>
            </h2>
          </div>
          <div class="col-auto ms-auto d-print-none">
          </div>
        </div>
      </div>
    </div>
    <div class="page-body">
      <div class="container-xl">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-body">
                <form action="{% url 'challenge_client:challenge-enroll' challenge.pk %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-primary">Enroll now</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/challenge/challenge_client/header.html
{% load core_tags %}
<header class="navbar navbar-expand-md navbar-light d-print-none">
  <div class="container-xl">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu"
            aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
      {% include site_title|default:'challenge/challenge_client/title.html' %}
    </h1>

    <div class="navbar-nav flex-row order-md-last">
      <div class="nav-item {% active_link_app 'blockchain' %}">
        <a class="nav-link" href="{% url 'blockchain:explorer' %}">
                    <span class="nav-link-title">
                                Blockchain Explorer
                              </span>
        </a>
      </div>
      <div class="nav-item">
        <a class="nav-link" href="{% url 'challenge_client:challenge-list' %}">
                    <span class="nav-link-title">
                                All challenges
                              </span>
        </a>
      </div>

      {% if not request.user.is_authenticated %}
        <div class="nav-item">
          <a class=" btn btn-primary" href="{% url 'account_login' %}">
                    <span class="nav-link-title">
                                Sign In
                              </span>
          </a>
        </div>

        {% settings 'IS_CHALLENGE_HUB' as is_hub %}
        {% settings 'HUB_ENABLE_REGISTRATION' as registration_enabled %}
        {% if is_hub and registration_enabled %}
          <div class="nav-item ms-2">
            <a class="btn btn-secondary" href="{% url 'challenge_client:register' %}">
                    <span class="nav-link-title">
                                Register
                              </span>
            </a>
          </div>
        {% endif %}

      {% endif %}
      {% if request.user.is_authenticated %}
        <div class="nav-item dropdown">
          <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown"
             aria-label="Open user menu">
            <div class="d-none d-xl-block ps-2">
              <div>{{ request.user.username }}</div>
            </div>
          </a>
          <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
            {% if request.user.is_superuser %}
              <a href="{% url 'admin:index' %}" class="dropdown-item">ADMIN</a>
            {% endif %}
            <a href="{% url 'user:profile:form' %}" class="dropdown-item">Profile</a>

            <div>
              <form action="{% url 'account_logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="dropdown-item">Sign out</button>
              </form>
            </div>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
</header>

templates/challenge/challenge_client/index.html
{% extends 'challenge/challenge_client/base.html' %}
{% load humanize challenge_client_tags %}
{% block content %}
  <div class="page-wrapper">
    <div class="page-header d-print-none">
      <div class="container-xl">
        <div class="row g-2 align-items-center">
          <div class="col">
            <h2 class="page-title">
              Challenges on this hub
            </h2>
          </div>
          <div class="col-auto ms-auto d-print-none">
          </div>
        </div>
      </div>
    </div>
    <div class="page-body">
      <div class="container-xl">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <table id="table" class="table table-striped table-hover" style="width:100%">
                <thead>
                <tr>
                  <th>Name</th>
                  <th>Organizer</th>
                  <th>Open since</th>
                  <th>Open until</th>
                  {#                  <th>Dataset</th>#}
                  {#                  <th></th>#}
                  {#                    <th class="">Tags</th>#}
                  <th class="w-1"></th>
                </tr>
                </thead>
                <tbody>
                {% for c in challenges %}
                  <tr>
                    <td>
                      <a href="{% url 'challenge_client:challenge-detail' c.pk %}">{{ c.name }}</a>
                      {% is_enrolled request c as en %}
                      {% if en %}
                        <span class="badge">Enrolled</span>
                      {% endif %}
                    </td>
                  <td>
                    {{ c.origin.human_readable }}
                    {% if c.origin.organization|length > 0 %}
                      ({{ c.origin.organization }})
                    {% endif %}
                  </td>
                    <td>{{ c.open_from|naturalday }}</td>
                    <td>{{ c.open_until|naturalday }}</td>
                    {#                    <td>{{ c.dataset_name }}</td>#}
                    {#                    <td>#}
                    {#                      {{ c.tags }}#}
                    {#                        {% for tag in c.tags_arr %}<kbd>{% if not forloop.first %}{% endif %}{{ tag }}</kbd>{% endfor %}</td>#}
                    <td>
                      <a href="{% url 'challenge_client:challenge-detail' c.pk %}" class="btn btn-secondary btn-icon"><i
                        class="ti ti-arrow-right"></i></a>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block navbar %}
{% endblock %}

templates/challenge/challenge_client/navbar.html
{% block navbar %}
  <header class="navbar-expand-md">
    <div class="collapse navbar-collapse" id="navbar-menu">
      <div class="navbar navbar-light">
        <div class="container-xl">
          {% include site_navigation|default:'challenge/challenge_client/site-navigation.html' %}
        </div>
      </div>
    </div>
  </header>
{% endblock %}

templates/challenge/challenge_client/site-navigation.html
{#<ul class="navbar-nav">#}
{#  <li class="nav-item active">#}
{#    <a class="nav-link" href="{% url 'challenge_client:challenge-list' %}">#}
{#        <span class="nav-link-title">#}
{#            Challenges#}
{#        </span>#}
{#    </a>#}
{#  </li>#}
{#  <li class="nav-item">#}
{#    <a class="nav-link" href="#">#}
{#        <span class="nav-link-title">#}
{#            Shared with me#}
{#          </span>#}
{#    </a>#}
{#  </li>#}
{#</ul>#}

templates/challenge/challenge_client/title.html
CENTAURON :: CHALLENGE :: HUB